### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 30000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "3db9ac2e24d34d2f9f4a7d98d1bd2ba7",
  "accountNumber": "1000000002",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/ae523fb173644529bcfbdf91cd3669ea
