### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ae523fb173644529bcfbdf91cd3669ea",
  "accountNumber": "1000000001",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/ae523fb173644529bcfbdf91cd3669ea
